/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.googlecode.lanterna:lanterna:3.1.1")
    testImplementation(platform("org.junit:junit-bom:5.7.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.1")
}

java {
    sourceSets {
        main {
            java.setSrcDirs(listOf("src/main"))
        }
        test {
            java.setSrcDirs(listOf("src/test"))
        }
    }
    sourceCompatibility = JavaVersion.VERSION_14
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "roguelike"

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.test {
    useJUnitPlatform()
}

